#ifndef SETTINGS_H
#define SETTINGS_H

#include <QPoint>
#include <QColor>

const qint32 WINDOW_WIDTH = 700;
const qint32 WINDOW_HEIGHT = 500;

//const QPoint LANDSCAPE_POINT1 = QPoint(0, WINDOW_HEIGHT);
//const QPoint LANDSCAPE_POINT2 = QPoint(WINDOW_WIDTH, 0);

const QPoint LANDSCAPE_POINT1 = QPoint(0, qrand() % ((WINDOW_HEIGHT + 1) - WINDOW_HEIGHT / 4) + WINDOW_HEIGHT / 4);
const qint32 LANDSCAPE_XPART1 = WINDOW_WIDTH / 4;
const qint32 LANDSCAPE_XPART2 = WINDOW_WIDTH / 2;
const qint32 LANDSCAPE_XPART3 = LANDSCAPE_XPART1 + LANDSCAPE_XPART2;
const QPoint LANDSCAPE_POINT2 = QPoint(WINDOW_WIDTH, qrand() % ((WINDOW_HEIGHT + 1) - 1) + 1);

const qreal LANDSCAPE_WIDTH = WINDOW_WIDTH;
const qreal LANDSCAPE_HEIGHT = WINDOW_HEIGHT;

const QColor LANDSCAPE_COLOR = QColor("yellow");

#endif // SETTINGS_H
